### ISSUE TITLE
could you release the potable qBittorrent-Enhanced-Edition?/能否出个便携版？

### ISSUE THREAD

**Issue by PS0123456** [c0re100/qBittorrent-Enhanced-Edition#62] opened 2019-11-02 04:41 UTC
**Please provide the following information**

### qBittorrent version and Operating System
the latest
windows.

### If on linux, libtorrent and Qt version
None

### What is the problem
It has been always the potable QB in my OS since my first time to use this cool software. The profile document is at the same place with the QB. If i want to update the QB, I usually will install the latest version, manually copy the related files to the folder of the potable version and then do the uninstallation process.  

### What is the expected behavior
I would appreciate that you directly release the latest potable version. This can save the process Of installation and uninstallation.

**Comment by abcfy2** [comment] 2019-11-02 10:34
解压exe安装包(比如用7-zip解压)，删掉无用的`$PLUGINSDIR`目录和dbg文件`qbittorrent.pdb`即可。

**Comment by PS0123456** [comment] 2019-11-02 16:39
> 解压exe安装包(比如用7-zip解压)，删掉无用的`$PLUGINSDIR`目录和dbg文件`qbittorrent.pdb`即可。

THX,i will try this.

**Comment by Paranioa** [comment] 2019-11-14 08:42
解压过后添加启动参数`--portable`

**Comment by myfreeer** [comment] 2019-11-17 12:58
Duplicate of #4

**Closed** 2019-12-19 23:13 UTC
